version: "3"
services:
  gitbase:
    container_name: gitbase
    hostname: gitbase
    image: srcd/gitbase:v0.20.0-rc2
    volumes: 
    - "./git-demos:/opt/repos"
    ports:
    - "3306:3306"
  postgres:
    image: postgres:9.6.11
    ports:
    - "5432:5432"
    environment:
    - "POSTGRES_PASSWORD:dalong"